modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/Ribbits/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
    credits="Thank you to the community for all your great ideas!"
    authors="Joosh, YUNGNICKYOUNG, HellionGames, Refresh Studios"
    description="${mod_description}"
    logoFile="icon.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/ribbits"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},1.21)"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${yungsapi_mc_version}-Forge-${yungsapi_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    versionRange="[${forge_geckolib_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"